version: '3.8'
services:

  gym:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    #ports:
    #  - 10000:10000
    environment:
      - TZ=Europe/Moscow
      #- PORT=10000
      #- CONFIG=paraphraser_bert
      #- CONFIG=paraphraser_rubert